defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: 127.0.0.1
  pool: 5
  username: root
  password: chimpance99

development:
  database: tiabotas2013_development
  socket: /tmp/mysql.sock
  <<: *defaults

test: &test
  database: tiabotas2013_test
  socket: /tmp/mysql.sock
  <<: *defaults

production:
  host: localhost
  database: tiabotas2013_production
  <<: *defaults
