require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CancionesController do

  # This should return the minimal set of attributes required to create a valid
  # Cancion. As you add validations to Cancion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "link" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CancionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all canciones as @canciones" do
      cancion = Cancion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:canciones).should eq([cancion])
    end
  end

  describe "GET show" do
    it "assigns the requested cancion as @cancion" do
      cancion = Cancion.create! valid_attributes
      get :show, {:id => cancion.to_param}, valid_session
      assigns(:cancion).should eq(cancion)
    end
  end

  describe "GET new" do
    it "assigns a new cancion as @cancion" do
      get :new, {}, valid_session
      assigns(:cancion).should be_a_new(Cancion)
    end
  end

  describe "GET edit" do
    it "assigns the requested cancion as @cancion" do
      cancion = Cancion.create! valid_attributes
      get :edit, {:id => cancion.to_param}, valid_session
      assigns(:cancion).should eq(cancion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cancion" do
        expect {
          post :create, {:cancion => valid_attributes}, valid_session
        }.to change(Cancion, :count).by(1)
      end

      it "assigns a newly created cancion as @cancion" do
        post :create, {:cancion => valid_attributes}, valid_session
        assigns(:cancion).should be_a(Cancion)
        assigns(:cancion).should be_persisted
      end

      it "redirects to the created cancion" do
        post :create, {:cancion => valid_attributes}, valid_session
        response.should redirect_to(Cancion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cancion as @cancion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cancion.any_instance.stub(:save).and_return(false)
        post :create, {:cancion => { "link" => "invalid value" }}, valid_session
        assigns(:cancion).should be_a_new(Cancion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cancion.any_instance.stub(:save).and_return(false)
        post :create, {:cancion => { "link" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cancion" do
        cancion = Cancion.create! valid_attributes
        # Assuming there are no other canciones in the database, this
        # specifies that the Cancion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cancion.any_instance.should_receive(:update_attributes).with({ "link" => "MyString" })
        put :update, {:id => cancion.to_param, :cancion => { "link" => "MyString" }}, valid_session
      end

      it "assigns the requested cancion as @cancion" do
        cancion = Cancion.create! valid_attributes
        put :update, {:id => cancion.to_param, :cancion => valid_attributes}, valid_session
        assigns(:cancion).should eq(cancion)
      end

      it "redirects to the cancion" do
        cancion = Cancion.create! valid_attributes
        put :update, {:id => cancion.to_param, :cancion => valid_attributes}, valid_session
        response.should redirect_to(cancion)
      end
    end

    describe "with invalid params" do
      it "assigns the cancion as @cancion" do
        cancion = Cancion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cancion.any_instance.stub(:save).and_return(false)
        put :update, {:id => cancion.to_param, :cancion => { "link" => "invalid value" }}, valid_session
        assigns(:cancion).should eq(cancion)
      end

      it "re-renders the 'edit' template" do
        cancion = Cancion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cancion.any_instance.stub(:save).and_return(false)
        put :update, {:id => cancion.to_param, :cancion => { "link" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cancion" do
      cancion = Cancion.create! valid_attributes
      expect {
        delete :destroy, {:id => cancion.to_param}, valid_session
      }.to change(Cancion, :count).by(-1)
    end

    it "redirects to the canciones list" do
      cancion = Cancion.create! valid_attributes
      delete :destroy, {:id => cancion.to_param}, valid_session
      response.should redirect_to(canciones_url)
    end
  end

end
